name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18.12.0
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.0"
      - run: npm ci
      - run: npm run test
